### ISSUE TITLE
Problems restore from backup, missing coins

### ISSUE THREAD

**Issue by markuspeloquin** [hank/litecoin-wallet#25]
Somehow when I restored from my backup with a clean install, only the last transaction was shown for http://block-explorer.com/address/LN4FFTEJqemnr1DUTDrbJDLvvrqLDTeobu

I reset my blockchain and the two earlier transactions showed up. Perhaps when restoring a backup, the app is only looking as far back as the most recent transaction, whereas resetting the blockchain is a more exhaustive operation?

**Comment by hank** [comment]
Yes, the way the wallet works, when you add a new address or restore a backup, you'll have to reset the blockchain to pull in the transactions.  This is because the phone itself doesn't store global blockchain transactions, just those relevant to the stored wallet.  You can read more about SPV wallets here:

http://bitcoin.stackexchange.com/a/4651/13268
