### ISSUE TITLE
Qr code capture can't find camera

### ISSUE THREAD

**Issue by weex** [hank/litecoin-wallet#9]
On a Galaxy Note II where the Bitcoin Wallet app is working, Litecoin Wallet says "The camera has a problem. You probably need to restart the device". Of course a restart didn't help.

**Comment by hank** [comment]
That's odd, since I didn't mess with that part of the code at all.  If you can get a logcat from the device, that could help.

**Comment by weex** [comment]
I tried removing the other app to no avail. I don't have adb anywhere but will try when I get a chance. Could it be some difference in how your app is built vs Bitcoin Wallet?

**Comment by hank** [comment]
Could be I guess, but I'm using maven the same way he was as far as I can tell.  The QRCode scanning feature works on my phone - I made sure to test it.  I'll check again tonight just to be sure.

**Comment by hank** [comment]
Just tried it, worked great.  Let me know if you get around to hooking it up to adb.

**Comment by hank** [comment]
So here's another person having an issue scanning QRcodes with a galaxy note:

http://stackoverflow.com/questions/15220355/zxing-issue-with-the-portrait-mode-for-the-samsung-galaxy-note

My app uses zxing - I think it may be a problem with that library.  I can see if there's an updated jar...

**Comment by hank** [comment]
I ran into this today (finally).  I think it is a difference in the build
process somewhere (has something to do with resolving the class - I have no
idea why.  Perhaps the class is being removed in my version because it's
only resolved at runtime from a string.  Anyway, I changed it so it always
uses the same class for the camera.  It fixed it on my phone, but if you
could try it (version 1.07) that would be great!

**Comment by hank** [comment]
Just tried on my Asus Transformer TF101 and it works nicely - uses the correct camera (back).

**Comment by weex** [comment]
Works for me too now. Nice work!

**Comment by hank** [comment]
Thanks - closing this out!
